<?
//////////////////////////////////////
//		Display Class				//
//////////////////////////////////////

// GENERIC TRANSLATE
define(DSP_GEN_YES, 			"Да");
define(DSP_GEN_NO,				"Не");
define(DSP_ALL_MONTH,			"Месец");
define(DSP_ALL_DAY,				"Ден");
define(DSP_ALL_YEAR,			"Година");
define(DSP_GEN_BTNVALID, 		"Ok");
define(DSP_GEN_BTNAPPLY, 		"Apply");
define(DSP_GEN_BETA, 			"Beta");
define(DSP_GEN_DATE, 			"Дата");

define(DSP_GEN_ALERT, 			"-= Важно съобщение =- \n\n Трябва предварително да създадете folder в Webanalyse директорията наречен log с разрешение CHMOD 0770 !\n моля прочетете ReadMeFirst преди да започнете.");
define(DSP_GEN_ALERT2, 			"За момента няма никакви статистики !");

define(DSP_GEN_SHORTMJAN, 		"Януари");
define(DSP_GEN_SHORTMFEB, 		"Февруари");
define(DSP_GEN_SHORTMMAR, 		"Март");
define(DSP_GEN_SHORTMAPR, 		"Април");
define(DSP_GEN_SHORTMMAY, 		"Май");
define(DSP_GEN_SHORTMJUN, 		"Юни");
define(DSP_GEN_SHORTMJUL, 		"Юли");
define(DSP_GEN_SHORTMAUG, 		"Август");
define(DSP_GEN_SHORTMSEP, 		"Септември");
define(DSP_GEN_SHORTMOCT, 		"Октомври");
define(DSP_GEN_SHORTMNOV, 		"Ноември");
define(DSP_GEN_SHORTMDEC, 		"Декември");


define(DSP_GEN_NBPAGE, 			"Преглед на страници");
define(DSP_GEN_NBHITS, 			"Брой на Hits");

// Function DisplayAll
define(DSP_ALL_DETAILS, 		"Детайли");
define(DSP_ALL_TOPT,			"Топ ");
define(DSP_ALL_BY,				"сорт.");

define(DSP_ALL_VISITBYDAY, 		"Посещения по дни за");

define(DSP_ALL_GRAPHALL, 		"Всичко");
define(DSP_ALL_GRAPHWITHREF, 	"С препратки");
define(DSP_ALL_GRAPHWITHNOREF, 	"Без препратки");

define(DSP_ALL_MOREGFX, 		"Още графики");

define(DSP_ALL_VISITPERHOUR, 	"Посещения по час");

define(DSP_ALL_BESTBRO, 		"Браузъри");
define(DSP_ALL_CNXON, 			"Статистика за");

// Function DisplayVisit
define(DSP_VISIT_TIME, 			"Време на пристигане");
define(DSP_VISIT_PAGEVIEW,		"бр. стр. прегледани");
define(DSP_VISIT_NBHIT,			"бр. Hits");
define(DSP_VISIT_REFERER,		"Препратки");
define(DSP_VISIT_BROWSER,		"Браузъри");
define(DSP_VISIT_TIMEALL,		"Времева статистика за страници");
define(DSP_VISIT_TIMEALL2, 		"Време на връзка");

// Function DisplaySelect
define(DSP_SEL_OPT, 			"Дисплей опции");
define(DSP_SEL_GFXON, 			"Графики Вкл.");
define(DSP_SEL_GFXOFF, 			"Графики Изкл.");

define(DSP_SEL_MODE, 			"Начин на показ");

define(DSP_SEL_MODEALL, 		"На кратко");
define(DSP_SEL_MODEDETAIL, 		"Детайли");
define(DSP_SEL_MODEPAGE, 		"Страници");


// Function DisplayHeader
define(DSP_HEADER_SETT, 		"Настройки");
define(DSP_HEADER_UPDATE, 		"Провери за нова версия");
define(DSP_HEADER_ABOUT, 		"Автори");

// Function DisplayYearTab
define(DSP_YEART_AV, 			"Години");

// Function DisplayMonthTab
define(DSP_MONTHT_AV, 			"Месеци");

// Function DisplayTotalDetails
define(DSP_DAYT_THIS, 			"Този");
define(DSP_DAYT_THIS2, 			"Тази");

define(DSP_DAYT_DAY, 			"Днес");
define(DSP_DAYT_MONTH, 			"Месец");
define(DSP_DAYT_YEAR, 			"Година");

define(DSP_DAYT_VISIT, 			"Посещения");
define(DSP_DAYT_HIT, 			"Hits");
define(DSP_DAYT_TIME, 			"Време на престой");
define(DSP_DAYT_AV, 			"Средно");

// Function DisplayDetailDay
define (DSP_DETAILD_NOENTRY, 	"Няма статистики");

define (DSP_DETAILD_TIME, 		"Час");
define (DSP_DETAILD_HOST, 		"Хост");
define (DSP_DETAILD_CLIENT, 	"Браузър");
define (DSP_DETAILD_DETAILS, 	"Детайли");
define (DSP_DETAILD_REF, 		"Идва от"); //REFERER

// Function DisplayHost
define (DSP_HOST_HOST, 			"Хост");

// Function DisplayReferer
define (DSP_HOST_REF, 			"Препратка");

// Function DisplayPage
define (DSP_PAGE_PAGE, 			"Страници");

// Function FormConfiguration
define (DSP_SETT_TITLE, 		"Default Settings");
define (DSP_SETT_INTLNG, 		"Език");
define (DSP_SETT_DSPGFX, 		"Показване на графики по подразбиране");

define (DSP_SETT_DEFNAV, 		"Навигация");
define (DSP_SETT_DEFNAV_CAL, 	"Календар");
define (DSP_SETT_DEFNAV_CLA, 	"Класическа");

define (DSP_SETT_TTENSORT, 		"Сортиране по");
define (DSP_SETT_NBTOP,			"Брой на записи в Топ");

define (DSP_CLASSDAY_VISIT,		"Посещение");

// Function Version
define (DSP_VERS_TITLE, 		"Провери за нова версия");
define (DSP_VERS_YOUR, 			"Вашата версия е");
define (DSP_VERS_LAST, 			"Най-нова версия");

define (DSP_VERS_NOCNX, 		"Невъзможо е да е свържа със сървъра ");
define (DSP_VERS_NONEW, 		"Имате последната версия но посетете все пак ");
define (DSP_VERS_NEW, 			"Нова версия е на Ваше разположение тук ");
define (DSP_VERS_CLOSE, 		"Затвори");

define (DSP_SETT_BLOCKIPTITLE,	"IP Филтър");
define (DSP_SETT_BLOCKIPACT,	"Активен IP филтър");
define (DSP_SETT_BLOCKIP,		"Добавете IP адрес който не искате да бъде отчетен от програмата.");
define (DSP_SETT_IP,			"IP адреси блокирани");
define (DSP_BTN_ADD,			"Добави");
?>
