<?
//////////////////////////////////////////
// Display Class, German //
// version 0.9 //
// done by Beate, bep@web.de // 
// http://www.paland.tv // 
//////////////////////////////////////////

// GENERIC TRANSLATE
define(DSP_GEN_YES, "Ja");
define(DSP_GEN_NO, "Nein");
define(DSP_ALL_MONTH, "Monat");
define(DSP_ALL_DAY, "Tag");
define(DSP_ALL_YEAR, "Jahr");
define(DSP_GEN_BTNVALID, "Ok");
define(DSP_GEN_BTNAPPLY, "Anwenden");
define(DSP_GEN_BETA, "Beta");
define(DSP_GEN_DATE, "Datum");

define(DSP_GEN_ALERT, "-= SEHR WICHTIG =- \n\n Es muss ein Unterordner 'log' im Ordner 'Webanalyse' erstellt werden, und dieser danach per CHMOD auf 0770 gesetzt werden!\n Lies die Datei 'ReadMeFirst' zuerst.");
define(DSP_GEN_ALERT2, "Die Web-Made hat keinen Eintrag gefunden, sorry !");

define(DSP_GEN_SHORTMJAN, "Jan");
define(DSP_GEN_SHORTMFEB, "Feb");
define(DSP_GEN_SHORTMMAR, "M&auml;r");
define(DSP_GEN_SHORTMAPR, "Apr");
define(DSP_GEN_SHORTMMAY, "Mai");
define(DSP_GEN_SHORTMJUN, "Jun");
define(DSP_GEN_SHORTMJUL, "Jul");
define(DSP_GEN_SHORTMAUG, "Aug");
define(DSP_GEN_SHORTMSEP, "Sep");
define(DSP_GEN_SHORTMOCT, "Okt");
define(DSP_GEN_SHORTMNOV, "Nov");
define(DSP_GEN_SHORTMDEC, "Dez");

define(DSP_GEN_NBPAGE, "dargstellte Seiten");
define(DSP_GEN_NBHITS, "Nb of Hits");

// Function DisplayAll
define(DSP_ALL_DETAILS, "Details");
define(DSP_ALL_TOPT, "Top ");
define(DSP_ALL_BY, "vom");

define(DSP_ALL_VISITBYDAY, "Besucher pro Tag im");

define(DSP_ALL_GRAPHALL, "Alle");
define(DSP_ALL_GRAPHWITHREF, "Mit Referer");
define(DSP_ALL_GRAPHWITHNOREF, "Ohne Referer");

define(DSP_ALL_MOREGFX, "Weitere Grafiken");

define(DSP_ALL_VISITPERHOUR, "Besucher pro Stunde");

define(DSP_ALL_BESTBRO, "Meistgenutze Browser");
define(DSP_ALL_CNXON, "Verbindung");

// Function DisplayVisit
define(DSP_VISIT_TIME, "Zeitpunkt");
define(DSP_VISIT_PAGEVIEW, "# angeschaute Seiten");
define(DSP_VISIT_NBHIT, "Anzahl der Hits");
define(DSP_VISIT_REFERER, "Referer");
define(DSP_VISIT_BROWSER, "Browser");
define(DSP_VISIT_TIMEALL, "Zeit der Verbindung pro Seite");
define(DSP_VISIT_TIMEALL2, "Zeit der Verbindung");

// Function DisplaySelect
define(DSP_SEL_OPT, "Anzeige-Optionen");
define(DSP_SEL_GFXON, "Grafiken an");
define(DSP_SEL_GFXOFF, "Grafiken aus");

define(DSP_SEL_MODE, "Anzeige-Modus");

define(DSP_SEL_MODEALL, "Allgemein");
define(DSP_SEL_MODEDETAIL, "Details");
define(DSP_SEL_MODEPAGE, "Seiten");

// Function DisplayHeader
define(DSP_HEADER_SETT, "Einstellungen");
define(DSP_HEADER_UPDATE, "Pr&uuml;fe auf Update");
define(DSP_HEADER_ABOUT, "&Uuml;ber");

// Function DisplayYearTab
define(DSP_YEART_AV, "vorhandene Jahre");

// Function DisplayMonthTab
define(DSP_MONTHT_AV, "vorhandene Monate");

// Function DisplayTotalDetails
define(DSP_DAYT_THIS, "Dieser");
define(DSP_DAYT_THIS2, 			"Dieses");

define(DSP_DAYT_DAY, "Heute");
define(DSP_DAYT_MONTH, "Monat");
define(DSP_DAYT_YEAR, "Jahr");

define(DSP_DAYT_VISIT, "Besuche");
define(DSP_DAYT_HIT, "Hits");
define(DSP_DAYT_TIME, "Zeit/Verbindung");
define(DSP_DAYT_AV, "Durchschnitt");

// Function DisplayDetailDay
define (DSP_DETAILD_NOENTRY, "kein Eintrag");

define (DSP_DETAILD_TIME, "Zeit");
define (DSP_DETAILD_HOST, "Host");
define (DSP_DETAILD_CLIENT, "Client");
define (DSP_DETAILD_DETAILS, "Detail");
define (DSP_DETAILD_REF, "Ref."); //REFERER

// Function DisplayHost
define (DSP_HOST_HOST, "Host");

// Function DisplayReferer
define (DSP_HOST_REF, "Referer");

// Function DisplayPage
define (DSP_PAGE_PAGE, "Seiten");

// Function FormConfiguration
define (DSP_SETT_TITLE, "Standard-Einstellung");
define (DSP_SETT_INTLNG, "Benutzte Sprache");
define (DSP_SETT_DSPGFX, "Zeige Grafiken standardm&auml;&szlig;ig an");

define (DSP_SETT_DEFNAV, "Standard-Navigation");
define (DSP_SETT_DEFNAV_CAL, "Kalender");
define (DSP_SETT_DEFNAV_CLA, "Classic");

define (DSP_SETT_TTENSORT, "Standard-Top-Ten sortiert nach");
define (DSP_SETT_NBTOP,			"Zahl der Anzeige Oberseite"); 

define (DSP_CLASSDAY_VISIT,		"Besuch"); 

define (DSP_SETT_BLOCKIPTITLE,		"Filter IP");
define (DSP_SETT_BLOCKIPACT,		"Aktiver IP-Adress-Filter");
define (DSP_SETT_BLOCKIP,			"Füge IP-Adresse hinzu, die nicht geloggt werden soll, wenn der IP-Filter aktiv ist.");
define (DSP_SETT_IP,				"IP-Adresse geblockt");
define (DSP_BTN_ADD,				"Füge");
?>