<?
//////////////////////////////////////
//		Display Class				//
//////////////////////////////////////

// GENERIC TRANSLATE
define(DSP_GEN_YES, 			"Si");
define(DSP_GEN_NO,			"No");
define(DSP_ALL_MONTH,			"Mes");
define(DSP_ALL_DAY,			"Dia");
define(DSP_ALL_YEAR,			"Año");
define(DSP_GEN_BTNVALID, 		"Ok");
define(DSP_GEN_BTNAPPLY, 		"Aplicar");
define(DSP_GEN_BETA, 			"Beta");
define(DSP_GEN_DATE, 			"Fecha");

define(DSP_GEN_ALERT, 			"-= MENSAJE MUY IMPORTANTE =- \n\n Tiene que crear en Webanalyse un informe llamado log con CHMOD 0770 !\n Lea por favor el fichero ReadMeFirst antes de empezar.");
define(DSP_GEN_ALERT2, 			"¡Sentimos decirle que no hay entrada conectada por el Maggot,ahora !");

define(DSP_GEN_SHORTMJAN, 		"Ene");
define(DSP_GEN_SHORTMFEB, 		"Feb");
define(DSP_GEN_SHORTMMAR, 		"Mar");
define(DSP_GEN_SHORTMAPR, 		"Apr");
define(DSP_GEN_SHORTMMAY, 		"Mayo");
define(DSP_GEN_SHORTMJUN, 		"Junio");
define(DSP_GEN_SHORTMJUL, 		"Julio");
define(DSP_GEN_SHORTMAUG, 		"Ago");
define(DSP_GEN_SHORTMSEP, 		"Sep");
define(DSP_GEN_SHORTMOCT, 		"Oct");
define(DSP_GEN_SHORTMNOV, 		"Nov");
define(DSP_GEN_SHORTMDEC, 		"Dic");


define(DSP_GEN_NBPAGE, 			"vista paginas");
define(DSP_GEN_NBHITS, 			"Num de Impactos");

// Function DisplayAll
define(DSP_ALL_DETAILS, 		"Detalles");
define(DSP_ALL_TOPT,			"Encima ");
define(DSP_ALL_BY,			"por");

define(DSP_ALL_VISITBYDAY, 		"Visitas  Diarias en");

define(DSP_ALL_GRAPHALL, 		"Todo");
define(DSP_ALL_GRAPHWITHREF, 		"Con Referer");
define(DSP_ALL_GRAPHWITHNOREF, 		"Sin Referer");

define(DSP_ALL_MOREGFX, 		"Mas graficos");

define(DSP_ALL_VISITPERHOUR, 		"Visitas por Horas");

define(DSP_ALL_BESTBRO, 		"Mejor Navegador");
define(DSP_ALL_CNXON, 			"Coneccion activada");

// Function DisplayVisit
define(DSP_VISIT_TIME, 			"Hora de Llegada");
define(DSP_VISIT_PAGEVIEW,		"# paginas vistas");
define(DSP_VISIT_NBHIT,			"Numero de impactos");
define(DSP_VISIT_REFERER,		"Referer");
define(DSP_VISIT_BROWSER,		"Navegador");
define(DSP_VISIT_TIMEALL,		"Tiempo de coneccion per pagina");
define(DSP_VISIT_TIMEALL2, 		"Tiempo de coneccion");

// Function DisplaySelect
define(DSP_SEL_OPT, 			"Opciones de Pantalla");
define(DSP_SEL_GFXON, 			"Graficos Activados");
define(DSP_SEL_GFXOFF, 			"Graficos Desactivados");

define(DSP_SEL_MODE, 			"Modo de la Pantalla");

define(DSP_SEL_MODEALL, 		"General");
define(DSP_SEL_MODEDETAIL, 		"Detalles");
define(DSP_SEL_MODEPAGE, 		"Paginas");


// Function DisplayHeader
define(DSP_HEADER_SETT, 		"Ajustes");
define(DSP_HEADER_UPDATE, 		"ChequearActualizacion");
define(DSP_HEADER_ABOUT, 		"Sobre");

// Function DisplayYearTab
define(DSP_YEART_AV, 			"Año disponible");

// Function DisplayMonthTab
define(DSP_MONTHT_AV, 			"Mes disponible");

// Function DisplayTotalDetails
define(DSP_DAYT_THIS, 			"Esto");
define(DSP_DAYT_THIS2, 			"Esto");

define(DSP_DAYT_DAY, 			"Hoy");
define(DSP_DAYT_MONTH, 			"Mes");
define(DSP_DAYT_YEAR, 			"Año");

define(DSP_DAYT_VISIT, 			"Visitas");
define(DSP_DAYT_HIT, 			"Impactos");
define(DSP_DAYT_TIME, 			"Tiempo/conexion");
define(DSP_DAYT_AV, 			"Mediados");

// Function DisplayDetailDay
define (DSP_DETAILD_NOENTRY, 		"No Entradas");

define (DSP_DETAILD_TIME, 		"Tiempo");
define (DSP_DETAILD_HOST, 		"Servidor");
define (DSP_DETAILD_CLIENT, 		"Cliente");
define (DSP_DETAILD_DETAILS, 		"Detalles");
define (DSP_DETAILD_REF, 		"Ref."); //REFERER

// Function DisplayHost
define (DSP_HOST_HOST, 			"Servidor");

// Function DisplayReferer
define (DSP_HOST_REF, 			"Referer");

// Function DisplayPage
define (DSP_PAGE_PAGE, 			"Paginas");

// Function FormConfiguration
define (DSP_SETT_TITLE, 		"Ajustes por defecto");
define (DSP_SETT_INTLNG, 		"Idioma de interface");
define (DSP_SETT_DSPGFX, 		"Monstrar graficos por defecto ");

define (DSP_SETT_DEFNAV, 		"Navegacion por defecto");
define (DSP_SETT_DEFNAV_CAL, 		"Calendario");
define (DSP_SETT_DEFNAV_CLA, 		"Clasico");

define (DSP_SETT_TTENSORT, 		"Sortear los Primeros Diez por defecto");
define (DSP_SETT_NBTOP,			"Numero de visualizaciones encimas"); 

define (DSP_CLASSDAY_VISIT,		"Visitas"); 

// Function Version
define (DSP_VERS_TITLE, 		"Verificar nueva version en Linea");
define (DSP_VERS_YOUR, 			"Su version es");
define (DSP_VERS_LAST, 			"Ultima version disponible");

define (DSP_VERS_NOCNX, 		"Imposible de chequear nueva version. Coneccion Imposible en ");
define (DSP_VERS_NONEW, 		"Vale, Tiene la ultima version ! Pero puede visitar el sitio por el 									placer ");
define (DSP_VERS_NEW, 			"Una nueva version es disponible se puede descargarla aqui ");
define (DSP_VERS_CLOSE, 		"Cerrar");

define (DSP_SETT_BLOCKIPTITLE,		"filtro IP");
define (DSP_SETT_BLOCKIPACT,		"filtro de direccion IP Activo");
define (DSP_SETT_BLOCKIP,			"Añadir Direccion IP que no  sera conectada si el filtro IP es activado");
define (DSP_SETT_IP,				"Direccion IP Bloqueada");
define (DSP_BTN_ADD,				"Añadir");

?>

