<?
//////////////////////////////////////
//		Display Class				//
//////////////////////////////////////

// GENERIC TRANSLATE
define(DSP_GEN_YES, 			"Oui");
define(DSP_GEN_NO,			"Non");
define(DSP_ALL_MONTH,			"Mois");
define(DSP_ALL_DAY,			"Jour");
define(DSP_ALL_YEAR,			"Année");
define(DSP_GEN_BTNVALID, 		"Ok");
define(DSP_GEN_BTNAPPLY, 		"Appliquer");
define(DSP_GEN_BETA, 			"Beta");
define(DSP_GEN_DATE, 			"Date");

define(DSP_GEN_ALERT, 			"-= MESSAGE IMPORTANT =- \n\n Vous devez créer un répértoire dans Webanalyse appellé log avec un CHMOD 0777 !\n Merci de consulter le ReadMeFirst avant de continuer l'installation.");
define(DSP_GEN_ALERT2, 			"Aucunes entrées loggé par Webanalyse pour le moment, désolé !");

define(DSP_GEN_SHORTMJAN, 		"Jan");
define(DSP_GEN_SHORTMFEB, 		"Feb");
define(DSP_GEN_SHORTMMAR, 		"Mar");
define(DSP_GEN_SHORTMAPR, 		"Avr");
define(DSP_GEN_SHORTMMAY, 		"Mai");
define(DSP_GEN_SHORTMJUN, 		"Jui");
define(DSP_GEN_SHORTMJUL, 		"Jui");
define(DSP_GEN_SHORTMAUG, 		"Aou");
define(DSP_GEN_SHORTMSEP, 		"Sep");
define(DSP_GEN_SHORTMOCT, 		"Oct");
define(DSP_GEN_SHORTMNOV, 		"Nov");
define(DSP_GEN_SHORTMDEC, 		"Dec");


define(DSP_GEN_NBPAGE, 			"Pages vues");
define(DSP_GEN_NBHITS, 			"Nb de Hits");

// Function DisplayAll
define(DSP_ALL_DETAILS, 		"Details");
define(DSP_ALL_TOPT,			"Top ");
define(DSP_ALL_BY,			"par");

define(DSP_ALL_VISITBYDAY, 		"Visites par jour sur");

define(DSP_ALL_GRAPHALL, 		"Tout");
define(DSP_ALL_GRAPHWITHREF, 		"Avec Referer");
define(DSP_ALL_GRAPHWITHNOREF, 		"Sans Referer");

define(DSP_ALL_MOREGFX, 		"Plus de graphiques");

define(DSP_ALL_VISITPERHOUR, 		"Visites par heure");

define(DSP_ALL_BESTBRO, 		"Meilleur Navigateur");
define(DSP_ALL_CNXON, 			"Connexion sur");

// Function DisplayVisit
define(DSP_VISIT_TIME, 			"Heure d'arrivé");
define(DSP_VISIT_PAGEVIEW,		"# pages vues");
define(DSP_VISIT_NBHIT,			"Nombre de Hits");
define(DSP_VISIT_REFERER,		"Referer");
define(DSP_VISIT_BROWSER,		"Navigateur");
define(DSP_VISIT_TIMEALL,		"Temps de connexion par page");
define(DSP_VISIT_TIMEALL2, 		"Temps de connexion");

// Function DisplaySelect
define(DSP_SEL_OPT, 			"Options d'affichage");
define(DSP_SEL_GFXON, 			"Graphique On");
define(DSP_SEL_GFXOFF, 			"Graphique Off");

define(DSP_SEL_MODE, 			"Mode d'affichage");

define(DSP_SEL_MODEALL, 		"Général");
define(DSP_SEL_MODEDETAIL, 		"Details");
define(DSP_SEL_MODEPAGE, 		"Pages");


// Function DisplayHeader
define(DSP_HEADER_SETT, 		"Options");
define(DSP_HEADER_UPDATE, 		"Verifier les mises à jour");
define(DSP_HEADER_ABOUT, 		"A propos");

// Function DisplayYearTab
define(DSP_YEART_AV, 			"Années disponibles");

// Function DisplayMonthTab
define(DSP_MONTHT_AV, 			"Mois disponibles");

// Function DisplayTotalDetails
define(DSP_DAYT_THIS, 			"Ce");
define(DSP_DAYT_THIS2, 			"Cette");

define(DSP_DAYT_DAY, 			"Jour");
define(DSP_DAYT_MONTH, 			"Mois");
define(DSP_DAYT_YEAR, 			"Année");

define(DSP_DAYT_VISIT, 			"Visites");
define(DSP_DAYT_HIT, 			"Hits");
define(DSP_DAYT_TIME, 			"Temps/cnx");
define(DSP_DAYT_AV, 			"Moyenne");

// Function DisplayDetailDay
define (DSP_DETAILD_NOENTRY, 		"Pas d'entrées");

define (DSP_DETAILD_TIME, 		"Temps");
define (DSP_DETAILD_HOST, 		"Host");
define (DSP_DETAILD_CLIENT, 		"Client");
define (DSP_DETAILD_DETAILS, 		"Detail");
define (DSP_DETAILD_REF, 		"Ref."); //REFERER

// Function DisplayHost
define (DSP_HOST_HOST, 			"Host");

// Function DisplayReferer
define (DSP_HOST_REF, 			"Referer");

// Function DisplayPage
define (DSP_PAGE_PAGE, 			"Pages");

// Function FormConfiguration
define (DSP_SETT_TITLE, 		"Paramètres par défaut");
define (DSP_SETT_INTLNG, 		"Langue");
define (DSP_SETT_DSPGFX, 		"Affichage des graphiques");

define (DSP_SETT_DEFNAV, 		"Navigation par defaut");
define (DSP_SETT_DEFNAV_CAL, 		"PHPCalendar");
define (DSP_SETT_DEFNAV_CLA, 		"Classique");

define (DSP_SETT_TTENSORT, 		"Top Ten par defaut");
define (DSP_SETT_NBTOP,			"Nombre de resultat"); 

define (DSP_CLASSDAY_VISIT,		"Visites"); 

// Function Version
define (DSP_VERS_TITLE, 		"Verifier les mises à jour");
define (DSP_VERS_YOUR, 			"Votre version est");
define (DSP_VERS_LAST, 			"Dernière version disponible");

define (DSP_VERS_NOCNX, 		"Impossible de verifier les nouvelles version, connexion impossible sur ");
define (DSP_VERS_NONEW, 		"Vous possèdez la dernière version !");
define (DSP_VERS_NEW, 			"Nouvelle version disponible, téléchargeable ici ");
define (DSP_VERS_CLOSE, 		"Fermer");

define (DSP_SETT_BLOCKIPTITLE,		"Filtrage IP");
define (DSP_SETT_BLOCKIPACT,		"Activer Filtrage Ip");
define (DSP_SETT_BLOCKIP,			"Ajouter les adresses que vous ne voulez pas logger dans webanalyse.");
define (DSP_SETT_IP,				"Adress Ip bloqués");
define (DSP_BTN_ADD,				"Ajouter");
?>