<?
//////////////////////////////////////
//		Display Class				//
//////////////////////////////////////

// GENERIC TRANSLATE
define(DSP_GEN_YES, 			"Да");
define(DSP_GEN_NO,				"Нет");
define(DSP_ALL_MONTH,			"Месяц");
define(DSP_ALL_DAY,				"День");
define(DSP_ALL_YEAR,			"Год");
define(DSP_GEN_BTNVALID, 		"Ok");
define(DSP_GEN_BTNAPPLY, 		"Apply");
define(DSP_GEN_BETA, 			"Бета");
define(DSP_GEN_DATE, 			"Дата");

define(DSP_GEN_ALERT, 			"-= ОЧЕНЬ ВАЖНОЕ СООБЩЕНИЕ =- \n\n Вы должны создать папку в Webanalyse названное log с CHMOD 0770 !\n please look at the file ReadMeFirst before starting.");
define(DSP_GEN_ALERT2, 			"Никакой вход не регистрировался Maggot для Момента, sorry !");

define(DSP_GEN_SHORTMJAN, 		"Янв");
define(DSP_GEN_SHORTMFEB, 		"Фев");
define(DSP_GEN_SHORTMMAR, 		"Март");
define(DSP_GEN_SHORTMAPR, 		"Апр");
define(DSP_GEN_SHORTMMAY, 		"Май");
define(DSP_GEN_SHORTMJUN, 		"Июнь");
define(DSP_GEN_SHORTMJUL, 		"Июль");
define(DSP_GEN_SHORTMAUG, 		"Авг");
define(DSP_GEN_SHORTMSEP, 		"Сент");
define(DSP_GEN_SHORTMOCT, 		"Окт");
define(DSP_GEN_SHORTMNOV, 		"Ноя");
define(DSP_GEN_SHORTMDEC, 		"Дек");


define(DSP_GEN_NBPAGE, 			"Просмотр Страниц");
define(DSP_GEN_NBHITS, 			"Количество Кликов");

// Function DisplayAll
define(DSP_ALL_DETAILS, 		"Детали");
define(DSP_ALL_TOPT,			"Верх ");
define(DSP_ALL_BY,				"за");

define(DSP_ALL_VISITBYDAY, 		"Визит за День на");

define(DSP_ALL_GRAPHALL, 		"Все");
define(DSP_ALL_GRAPHWITHREF, 	"С Referer");
define(DSP_ALL_GRAPHWITHNOREF, 	"Без Referer");

define(DSP_ALL_MOREGFX, 		"Больше Графики");

define(DSP_ALL_VISITPERHOUR, 	"Визит за Час");

define(DSP_ALL_BESTBRO, 		"Наилучшее Browser");
define(DSP_ALL_CNXON, 			"Связь на");

// Function DisplayVisit
define(DSP_VISIT_TIME, 			"Час прибытия");
define(DSP_VISIT_PAGEVIEW,		"# просмотр страниц");
define(DSP_VISIT_NBHIT,			"Количество Хитов");
define(DSP_VISIT_REFERER,		"Referer");
define(DSP_VISIT_BROWSER,		"Browser");
define(DSP_VISIT_TIMEALL,		"Время связи за страницы");
define(DSP_VISIT_TIMEALL2, 		"Время связи");

// Function DisplaySelect
define(DSP_SEL_OPT, 			"Дисплейные Выборы");
define(DSP_SEL_GFXON, 			"Graphic Вкл");
define(DSP_SEL_GFXOFF, 			"Graphic Вьiкл");

define(DSP_SEL_MODE, 			"Режим Дисплея");

define(DSP_SEL_MODEALL, 		"Общее");
define(DSP_SEL_MODEDETAIL, 		"Детали");
define(DSP_SEL_MODEPAGE, 		"Страницы");


// Function DisplayHeader
define(DSP_HEADER_SETT, 		"Settings");
define(DSP_HEADER_UPDATE, 		"Check Update");
define(DSP_HEADER_ABOUT, 		"Об авторах");

// Function DisplayYearTab
define(DSP_YEART_AV, 			"Год");

// Function DisplayMonthTab
define(DSP_MONTHT_AV, 			"Месяц");

// Function DisplayTotalDetails
define(DSP_DAYT_THIS, 			"Этот");
define(DSP_DAYT_THIS2, 			"Этот");

define(DSP_DAYT_DAY, 			"Сегодня");
define(DSP_DAYT_MONTH, 			"Месяц");
define(DSP_DAYT_YEAR, 			"Год");

define(DSP_DAYT_VISIT, 			"Визит");
define(DSP_DAYT_HIT, 			"Хитов");
define(DSP_DAYT_TIME, 			"Время/связ");
define(DSP_DAYT_AV, 			"Среднее");

// Function DisplayDetailDay
define (DSP_DETAILD_NOENTRY, 	"Никакой Запис");

define (DSP_DETAILD_TIME, 		"Время");
define (DSP_DETAILD_HOST, 		"Host");
define (DSP_DETAILD_CLIENT, 	"Клиент");
define (DSP_DETAILD_DETAILS, 	"Деталь");
define (DSP_DETAILD_REF, 		"Ref."); //REFERER

// Function DisplayHost
define (DSP_HOST_HOST, 			"Host");

// Function DisplayReferer
define (DSP_HOST_REF, 			"Referer");

// Function DisplayPage
define (DSP_PAGE_PAGE, 			"Страницы");

// Function FormConfiguration
define (DSP_SETT_TITLE, 		"Default Settings");
define (DSP_SETT_INTLNG, 		"Язык Интерфейса");
define (DSP_SETT_DSPGFX, 		"Графику Вкл");

define (DSP_SETT_DEFNAV, 		"Навигация");
define (DSP_SETT_DEFNAV_CAL, 	"Календарь");
define (DSP_SETT_DEFNAV_CLA, 	"Классик");

define (DSP_SETT_TTENSORT, 		"Верхние Десять сортируется");
define (DSP_SETT_NBTOP,			"Номер дисплейного верха");

define (DSP_CLASSDAY_VISIT,		"Визит");

// Function Version
define (DSP_VERS_TITLE, 		"Проверьте новую версию Online");
define (DSP_VERS_YOUR, 			"Ваша версия");
define (DSP_VERS_LAST, 			"Последняя версия availabe");

define (DSP_VERS_NOCNX, 		"Невозможный, чтобы проверить новую версию. Связь невозможная на ");
define (DSP_VERS_NONEW, 		"Это - ok, у вас есть последняя версия! Но Вы можете посетить для шутки ");
define (DSP_VERS_NEW, 			"Новая версия доступна, Вы можете загрузить это здесь ");
define (DSP_VERS_CLOSE, 		"Закрыть");

define (DSP_SETT_BLOCKIPTITLE,	"IP Фильтр");
define (DSP_SETT_BLOCKIPACT,	"Активный фильтр IP Адреса");
define (DSP_SETT_BLOCKIP,		"Дополнение адреса IP, которое Вы не хотите зарегистрировать если фильтр ip активный.");
define (DSP_SETT_IP,			"Блокированный Адрес IP");
define (DSP_BTN_ADD,			"Дополнение");
?>
