<?
//////////////////////////////////////
//		Display Class				//
//////////////////////////////////////

// Function DisplayAll
define(DSP_ALL_DETAILS, 		"<font color='FF0000'>XXXXXXXXXXXXXXX</font>");
define(DSP_ALL_TOPT,			"<font color='FF0000'>XXXXXXXXXXXXXXXXX</font>");
define(DSP_ALL_BY,				"<font color='FF0000'>XXXXXXXXXXXXX</font>");

define(DSP_ALL_MONTH,			"<font color='FF0000'>XXXXXXXXXXXXX</font>");
define(DSP_ALL_DAY,				"<font color='FF0000'>XXXXXXXXXXXXXX</font>");
define(DSP_ALL_YEAR,			"<font color='FF0000'>XXXXXXXXXXXX</font>");

define(DSP_ALL_VISITBYDAY, 		"<font color='FF0000'>XXXXXXXX</font>");

define(DSP_ALL_GRAPHALL, 		"<font color='FF0000'>XXXXXXXXXXXXX</font>");
define(DSP_ALL_GRAPHWITHREF, 	"<font color='FF0000'>XXXXXXXXXXXXXX</font>");
define(DSP_ALL_GRAPHWITHNOREF, 	"<font color='FF0000'>XXXXX</font>");

define(DSP_ALL_MOREGFX, 		"<font color='FF0000'>XXXXXXXXXX</font>");

define(DSP_ALL_VISITPERHOUR, 	"<font color='FF0000'>XXXXXXXXXXXX</font>");

define(DSP_ALL_BESTBRO, 		"<font color='FF0000'>XXXXXXXXXX</font>");
define(DSP_ALL_CNXON, 			"<font color='FF0000'>XXXXXXXXXXX</font>");
?>