<?
//////////////////////////////////////
//		Display Class				//
//////////////////////////////////////

// GENERIC TRANSLATE
define(DSP_GEN_YES, 			"Yes");
define(DSP_GEN_NO,				"No");
define(DSP_ALL_MONTH,			"Month");
define(DSP_ALL_DAY,				"Day");
define(DSP_ALL_YEAR,			"Year");
define(DSP_GEN_BTNVALID, 		"Ok");
define(DSP_GEN_BTNAPPLY, 		"Apply");
define(DSP_GEN_BETA, 			"Beta");
define(DSP_GEN_DATE, 			"Date");

define(DSP_GEN_ALERT, 			"-= VERY IMPORTANT MESSAGE =- \n\n You must create a folder in Webanalyse called log with CHMOD 0770 !\n please look at the file ReadMeFirst before starting.");
define(DSP_GEN_ALERT2, 			"No entry logged by the Maggot for the Moment, sorry !");

define(DSP_GEN_SHORTMJAN, 		"Jan");
define(DSP_GEN_SHORTMFEB, 		"Feb");
define(DSP_GEN_SHORTMMAR, 		"Mar");
define(DSP_GEN_SHORTMAPR, 		"Apr");
define(DSP_GEN_SHORTMMAY, 		"May");
define(DSP_GEN_SHORTMJUN, 		"Jun");
define(DSP_GEN_SHORTMJUL, 		"Jul");
define(DSP_GEN_SHORTMAUG, 		"Aug");
define(DSP_GEN_SHORTMSEP, 		"Sep");
define(DSP_GEN_SHORTMOCT, 		"Oct");
define(DSP_GEN_SHORTMNOV, 		"Nov");
define(DSP_GEN_SHORTMDEC, 		"Dec");


define(DSP_GEN_NBPAGE, 			"Pages view");
define(DSP_GEN_NBHITS, 			"Nb of Hits");

// Function DisplayAll
define(DSP_ALL_DETAILS, 		"Details");
define(DSP_ALL_TOPT,			"Top ");
define(DSP_ALL_BY,				"by");

define(DSP_ALL_VISITBYDAY, 		"Visit per Day on");

define(DSP_ALL_GRAPHALL, 		"All");
define(DSP_ALL_GRAPHWITHREF, 	"With Referer");
define(DSP_ALL_GRAPHWITHNOREF, 	"Without Referer");

define(DSP_ALL_MOREGFX, 		"More Graphics");

define(DSP_ALL_VISITPERHOUR, 	"Visit per Hour");

define(DSP_ALL_BESTBRO, 		"Best Browser");
define(DSP_ALL_CNXON, 			"Connexion on");

// Function DisplayVisit
define(DSP_VISIT_TIME, 			"Hour of arrival");
define(DSP_VISIT_PAGEVIEW,		"# pages view");
define(DSP_VISIT_NBHIT,			"Number of Hits");
define(DSP_VISIT_REFERER,		"Referer");
define(DSP_VISIT_BROWSER,		"Browser");
define(DSP_VISIT_TIMEALL,		"Time of connexion per pages");
define(DSP_VISIT_TIMEALL2, 		"Time of connexion");

// Function DisplaySelect
define(DSP_SEL_OPT, 			"Display Options");
define(DSP_SEL_GFXON, 			"Graphic On");
define(DSP_SEL_GFXOFF, 			"Graphic Off");

define(DSP_SEL_MODE, 			"Display Mode");

define(DSP_SEL_MODEALL, 		"Général");
define(DSP_SEL_MODEDETAIL, 		"Details");
define(DSP_SEL_MODEPAGE, 		"Pages");


// Function DisplayHeader
define(DSP_HEADER_SETT, 		"Settings");
define(DSP_HEADER_UPDATE, 		"CheckUpdate");
define(DSP_HEADER_ABOUT, 		"About");

// Function DisplayYearTab
define(DSP_YEART_AV, 			"Year available");

// Function DisplayMonthTab
define(DSP_MONTHT_AV, 			"Month available");

// Function DisplayTotalDetails
define(DSP_DAYT_THIS, 			"This");
define(DSP_DAYT_THIS2, 			"This");

define(DSP_DAYT_DAY, 			"Today");
define(DSP_DAYT_MONTH, 			"Month");
define(DSP_DAYT_YEAR, 			"Year");

define(DSP_DAYT_VISIT, 			"Visits");
define(DSP_DAYT_HIT, 			"Hits");
define(DSP_DAYT_TIME, 			"Time/cnx");
define(DSP_DAYT_AV, 			"Average");

// Function DisplayDetailDay
define (DSP_DETAILD_NOENTRY, 	"No Entry");

define (DSP_DETAILD_TIME, 		"Time");
define (DSP_DETAILD_HOST, 		"Host");
define (DSP_DETAILD_CLIENT, 	"Client");
define (DSP_DETAILD_DETAILS, 	"Detail");
define (DSP_DETAILD_REF, 		"Ref."); //REFERER

// Function DisplayHost
define (DSP_HOST_HOST, 			"Host");

// Function DisplayReferer
define (DSP_HOST_REF, 			"Referer");

// Function DisplayPage
define (DSP_PAGE_PAGE, 			"Pages");

// Function FormConfiguration
define (DSP_SETT_TITLE, 		"Default Settings");
define (DSP_SETT_INTLNG, 		"Interface Language");
define (DSP_SETT_DSPGFX, 		"Display Graphics by default");

define (DSP_SETT_DEFNAV, 		"Default navigation");
define (DSP_SETT_DEFNAV_CAL, 	"Calendar");
define (DSP_SETT_DEFNAV_CLA, 	"Classic");

define (DSP_SETT_TTENSORT, 		"Default Top Ten sort by");
define (DSP_SETT_NBTOP,			"Number of display top"); 

define (DSP_CLASSDAY_VISIT,		"Visit"); 

// Function Version
define (DSP_VERS_TITLE, 		"Check new version Online");
define (DSP_VERS_YOUR, 			"Your version is");
define (DSP_VERS_LAST, 			"Last version availabe");

define (DSP_VERS_NOCNX, 		"Impossible to check new version. Connexion impossible on ");
define (DSP_VERS_NONEW, 		"It's ok, you have a last version ! But you can visit for fun ");
define (DSP_VERS_NEW, 			"A new version is available, you can download it here ");
define (DSP_VERS_CLOSE, 		"Close");

define (DSP_SETT_BLOCKIPTITLE,	"Ip Filter");
define (DSP_SETT_BLOCKIPACT,	"Active ip Adress filter");
define (DSP_SETT_BLOCKIP,		"Add IP address which you don't want to log if ip filter is active.");
define (DSP_SETT_IP,			"Adress Ip blocked");
define (DSP_BTN_ADD,			"Add");
?>